# Generated by Django 5.0.3 on 2025-08-07 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='is_long_term',
            field=models.BooleanField(default=False),
        ),
    ]
