# Generated by Django 5.0.3 on 2025-08-15 18:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retire_app', '0004_alter_retirementplan_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='retirementincomesource',
            constraint=models.UniqueConstraint(fields=('user', 'income_source'), name='unique_user_income_source'),
        ),
    ]
