# Generated by Django 5.0.3 on 2025-08-18 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retire_app', '0005_retirementincomesource_unique_user_income_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='retirementplan',
            name='readiness',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
