# Generated by Django 5.0.3 on 2025-08-07 22:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income_source_name', models.CharField(max_length=100)),
                ('income_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expense_name', models.CharField(max_length=100)),
                ('expense_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deduction_name', models.CharField(max_length=100)),
                ('deduction_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('col_zip', models.IntegerField(max_length=5)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
