# Generated by Django 5.0.3 on 2025-08-12 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='contribution',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
